secretKey: "${SECRET_KEY}"
accessTokenTime: "60000"
refreshTokenTime: "604800000"

server:
  port: "8080"

spring:
  datasource:
    url: "jdbc:mysql://${DB_URL}:${DB_PORT}/chatbot?serverTimezone=Asia/Seoul"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

logging:
  level:
    Account: "warn"

